[package]
name = "squirrel"
version = "0.1.0"
authors = ["Brendon Oleary <brendon@seatgeek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = "0.4.0"
Inflector = "0.11.4"
